# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Test Deploy CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: npm test
    - run: cp .npmrc-publish ~/.npmrc
    - run: npm run pub
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_USER: ${{ secrets.NPM_USER }}
